picfilename_low: .byte <filename00,<filename01,<filename02,<filename03,<filename04,<filename05,<filename06,<filename07,<filename08,<filename09,<filename10,<filename11,<filename12,<filename13,<filename14,<filename15,<filename16,<filename17,<filename18,<filename19,<filename20,<filename21,<filename22,<filename23,<filename24,<filename25,<filename26,<filename27,<filename28,<filename29

picfilename_high: .byte >filename00,>filename01,>filename02,>filename03,>filename04,>filename05,>filename06,>filename07,>filename08,>filename09,>filename10,>filename11,>filename12,>filename13,>filename14,>filename15,>filename16,>filename17,>filename18,>filename19,>filename20,>filename21,>filename22,>filename23,>filename24,>filename25,>filename26,>filename27,>filename28,>filename29

filename00:
    .byte "00"
filename00_len = 2

filename01:
    .byte "01"
filename01_len = 2

filename02:
    .byte "02"
filename02_len = 2

filename03:
    .byte "03"
filename03_len = 2

filename04:
    .byte "04"
filename04_len = 2

filename05:
    .byte "05"
filename05_len = 2

filename06:
    .byte "06"
filename06_len = 2

filename07:
    .byte "07"
filename07_len = 2

filename08:
    .byte "08"
filename08_len = 2

filename09:
    .byte "09"
filename09_len = 2

filename10:
    .byte "10"
filename10_len = 2

filename11:
    .byte "11"
filename11_len = 2

filename12:
    .byte "12"
filename12_len = 2

filename13:
    .byte "13"
filename13_len = 2

filename14:
    .byte "14"
filename14_len = 2

filename15:
    .byte "15"
filename15_len = 2

filename16:
    .byte "16"
filename16_len = 2

filename17:
    .byte "17"
filename17_len = 2

filename18:
    .byte "18"
filename18_len = 2

filename19:
    .byte "19"
filename19_len = 2

filename20:
    .byte "20"
filename20_len = 2

filename21:
    .byte "21"
filename21_len = 2

filename22:
    .byte "22"
filename22_len = 2

filename23:
    .byte "23"
filename23_len = 2

filename24:
    .byte "24"
filename24_len = 2

filename25:
    .byte "25"
filename25_len = 2

filename26:
    .byte "26"
filename26_len = 2

filename27:
    .byte "27"
filename27_len = 2

filename28:
    .byte "28"
filename28_len = 2

filename29:
    .byte "29"
filename29_len = 2
